// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string           `json:"id"`
	Accountid             string           `json:"accountid"`
	Providerid            string           `json:"providerid"`
	Userid                string           `json:"userid"`
	Accesstoken           pgtype.Text      `json:"accesstoken"`
	Refreshtoken          pgtype.Text      `json:"refreshtoken"`
	Idtoken               pgtype.Text      `json:"idtoken"`
	Accesstokenexpiresat  pgtype.Timestamp `json:"accesstokenexpiresat"`
	Refreshtokenexpiresat pgtype.Timestamp `json:"refreshtokenexpiresat"`
	Scope                 pgtype.Text      `json:"scope"`
	Password              pgtype.Text      `json:"password"`
	Createdat             pgtype.Timestamp `json:"createdat"`
	Updatedat             pgtype.Timestamp `json:"updatedat"`
}

type Run struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    string           `json:"userId"`
	Data      []byte           `json:"data"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	Image     string           `json:"image"`
	Deleted   bool             `json:"deleted"`
}

type Session struct {
	ID             string           `json:"id"`
	Expiresat      pgtype.Timestamp `json:"expiresat"`
	Token          string           `json:"token"`
	Createdat      pgtype.Timestamp `json:"createdat"`
	Updatedat      pgtype.Timestamp `json:"updatedat"`
	Ipaddress      pgtype.Text      `json:"ipaddress"`
	Useragent      pgtype.Text      `json:"useragent"`
	Userid         string           `json:"userid"`
	Impersonatedby pgtype.Text      `json:"impersonatedby"`
}

type User struct {
	ID              string           `json:"id"`
	Name            string           `json:"name"`
	Email           string           `json:"email"`
	Emailverified   bool             `json:"emailverified"`
	Image           pgtype.Text      `json:"image"`
	Createdat       pgtype.Timestamp `json:"createdat"`
	Updatedat       pgtype.Timestamp `json:"updatedat"`
	Role            pgtype.Text      `json:"role"`
	Banned          pgtype.Bool      `json:"banned"`
	Banreason       pgtype.Text      `json:"banreason"`
	Banexpires      pgtype.Timestamp `json:"banexpires"`
	Username        pgtype.Text      `json:"username"`
	Displayusername pgtype.Text      `json:"displayusername"`
}

type Verification struct {
	ID         string           `json:"id"`
	Identifier string           `json:"identifier"`
	Value      string           `json:"value"`
	Expiresat  pgtype.Timestamp `json:"expiresat"`
	Createdat  pgtype.Timestamp `json:"createdat"`
	Updatedat  pgtype.Timestamp `json:"updatedat"`
}
