// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string           `json:"id"`
	AccountId             string           `json:"accountId"`
	ProviderId            string           `json:"providerId"`
	UserId                string           `json:"userId"`
	AccessToken           *string          `json:"accessToken"`
	RefreshToken          *string          `json:"refreshToken"`
	IdToken               *string          `json:"idToken"`
	AccessTokenExpiresAt  pgtype.Timestamp `json:"accessTokenExpiresAt"`
	RefreshTokenExpiresAt pgtype.Timestamp `json:"refreshTokenExpiresAt"`
	Scope                 *string          `json:"scope"`
	Password              *string          `json:"password"`
	CreatedAt             pgtype.Timestamp `json:"createdAt"`
	UpdatedAt             pgtype.Timestamp `json:"updatedAt"`
}

type Run struct {
	ID        pgtype.UUID      `json:"id"`
	UserId    string           `json:"userId"`
	Accepted  bool             `json:"accepted"`
	Data      []byte           `json:"data"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	Image     *string          `json:"image"`
	Deleted   bool             `json:"deleted"`
}

type Session struct {
	ID             string           `json:"id"`
	ExpiresAt      pgtype.Timestamp `json:"expiresAt"`
	Token          string           `json:"token"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp `json:"updatedAt"`
	IpAddress      *string          `json:"ipAddress"`
	UserAgent      *string          `json:"userAgent"`
	UserId         string           `json:"userId"`
	ImpersonatedBy *string          `json:"impersonatedBy"`
}

type User struct {
	ID              string           `json:"id"`
	Name            string           `json:"name"`
	Email           string           `json:"email"`
	EmailVerified   bool             `json:"emailVerified"`
	Image           *string          `json:"image"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	UpdatedAt       pgtype.Timestamp `json:"updatedAt"`
	Role            *string          `json:"role"`
	Banned          *bool            `json:"banned"`
	BanReason       *string          `json:"banReason"`
	BanExpires      pgtype.Timestamp `json:"banExpires"`
	Username        *string          `json:"username"`
	DisplayUsername *string          `json:"displayUsername"`
}

type Verification struct {
	ID         string           `json:"id"`
	Identifier string           `json:"identifier"`
	Value      string           `json:"value"`
	ExpiresAt  pgtype.Timestamp `json:"expiresAt"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
}
