// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRun = `-- name: DeleteRun :exec
UPDATE runs
SET "deleted" = true
WHERE "id" = $1
`

func (q *Queries) DeleteRun(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRun, id)
	return err
}

const getAllRunsWithUsers = `-- name: GetAllRunsWithUsers :many
SELECT 
    r."id", 
    r."data", 
    r."image", 
    r."createdAt",
    u."id" as "userId",
    u."name" as "user_name",
    u."displayUsername" as "user_username"
FROM runs r
LEFT JOIN "user" u ON r."userId" = u."id"
WHERE NOT r.deleted AND r.accepted
ORDER BY r."createdAt" DESC
`

type GetAllRunsWithUsersRow struct {
	ID           pgtype.UUID      `json:"id"`
	Data         []byte           `json:"data"`
	Image        *string          `json:"image"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UserId       *string          `json:"userId"`
	UserName     *string          `json:"userName"`
	UserUsername *string          `json:"userUsername"`
}

func (q *Queries) GetAllRunsWithUsers(ctx context.Context) ([]GetAllRunsWithUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllRunsWithUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRunsWithUsersRow
	for rows.Next() {
		var i GetAllRunsWithUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Data,
			&i.Image,
			&i.CreatedAt,
			&i.UserId,
			&i.UserName,
			&i.UserUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentRunsForUser = `-- name: GetRecentRunsForUser :many
SELECT "id", "userId", "data", "createdAt", "image" 
FROM runs 
WHERE "userId" = $1
ORDER BY "createdAt" DESC
LIMIT $2
`

type GetRecentRunsForUserParams struct {
	UserId string `json:"userId"`
	Limit  int32  `json:"limit"`
}

type GetRecentRunsForUserRow struct {
	ID        pgtype.UUID      `json:"id"`
	UserId    string           `json:"userId"`
	Data      []byte           `json:"data"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	Image     *string          `json:"image"`
}

func (q *Queries) GetRecentRunsForUser(ctx context.Context, arg GetRecentRunsForUserParams) ([]GetRecentRunsForUserRow, error) {
	rows, err := q.db.Query(ctx, getRecentRunsForUser, arg.UserId, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentRunsForUserRow
	for rows.Next() {
		var i GetRecentRunsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.Data,
			&i.CreatedAt,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunsByUserId = `-- name: GetRunsByUserId :many
SELECT "id", "userId", "data", "createdAt", "image" 
FROM runs 
WHERE "userId" = $1
ORDER BY "createdAt" DESC
`

type GetRunsByUserIdRow struct {
	ID        pgtype.UUID      `json:"id"`
	UserId    string           `json:"userId"`
	Data      []byte           `json:"data"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	Image     *string          `json:"image"`
}

func (q *Queries) GetRunsByUserId(ctx context.Context, userid string) ([]GetRunsByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getRunsByUserId, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRunsByUserIdRow
	for rows.Next() {
		var i GetRunsByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.Data,
			&i.CreatedAt,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one
SELECT "id", "name", "username" 
FROM "user" 
WHERE "id" = $1
`

type GetUserByIdRow struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Username *string `json:"username"`
}

func (q *Queries) GetUserById(ctx context.Context, id string) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(&i.ID, &i.Name, &i.Username)
	return i, err
}

const saveRun = `-- name: SaveRun :one
INSERT INTO runs ("userId", "data", "image", "createdAt")
VALUES ($1, $2, $3, NOW())
RETURNING "id", "userId", "data", "createdAt", "image"
`

type SaveRunParams struct {
	UserId string  `json:"userId"`
	Data   []byte  `json:"data"`
	Image  *string `json:"image"`
}

type SaveRunRow struct {
	ID        pgtype.UUID      `json:"id"`
	UserId    string           `json:"userId"`
	Data      []byte           `json:"data"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	Image     *string          `json:"image"`
}

func (q *Queries) SaveRun(ctx context.Context, arg SaveRunParams) (SaveRunRow, error) {
	row := q.db.QueryRow(ctx, saveRun, arg.UserId, arg.Data, arg.Image)
	var i SaveRunRow
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Data,
		&i.CreatedAt,
		&i.Image,
	)
	return i, err
}

const searchUsersByName = `-- name: SearchUsersByName :many
SELECT "id", "name", "username", "displayUsername"
FROM "user"
WHERE "name" ILIKE '%' || $1 || '%' OR "username" ILIKE '%' || $1 || '%'
ORDER BY "name"
LIMIT $2
`

type SearchUsersByNameParams struct {
	Column1 *string `json:"column1"`
	Limit   int32   `json:"limit"`
}

type SearchUsersByNameRow struct {
	ID              string  `json:"id"`
	Name            string  `json:"name"`
	Username        *string `json:"username"`
	DisplayUsername *string `json:"displayUsername"`
}

func (q *Queries) SearchUsersByName(ctx context.Context, arg SearchUsersByNameParams) ([]SearchUsersByNameRow, error) {
	rows, err := q.db.Query(ctx, searchUsersByName, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersByNameRow
	for rows.Next() {
		var i SearchUsersByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.DisplayUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
